### PR TITLE
Allow installing MbedTLS v1

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Comment by giordano** [comment]
Note that CI is not using MbedTLS v1 because of the Manifest.....

**Comment by DilumAluthge** [comment]
> Note that CI is not using MbedTLS v1 because of the Manifest.....

Can you clone the repository locally and do a package update? That should bump the version in the manifest.

**Comment by giordano** [comment]
Yes, it took 5 minutes of extra work to do it

**Comment by giordano** [comment]
Ok, now `MbetTLS.jl` v1 has been picked up correctly

**Comment by DilumAluthge** [comment]
Good to merge?

**Comment by giordano** [comment]
For me yes, I don't know whether you're asking someone else :sweat_smile:

**Pull request merged**
