### PR TITLE
Make trigger phrase case-insensitive

### PR DESCRIPTION
**Pull request by christopher-dG**
This lets us use `@juliaregistrator register` (fixes a gripe mentioned on Slack).

### CODE REVIEW

**Comment by nickrobinson251** [comment]
Could do with a test?

**Comment by christopher-dG** [comment]
I'm not actually sure how to approach that. The trigger is passed into GitHub.jl's `CommentListener` and not something that Registrator owns.

**Comment by DilumAluthge** [comment]
Maybe a simple test that confirms that this regex does match `JuliaRegistrator` and `juliaregistrator`, and does not match `ZuliaRegistrator` or `zuliaregistrator`.

**Comment by christopher-dG** [comment]
Good idea!

**Comment by christopher-dG** [comment]
I'm gonna go ahead and merge this tomorrow if no one has objections.

**Pull request merged**
