### PR TITLE
Remove restriction that repos must end with .jl.

### PR DESCRIPTION
**Pull request by fredrikekre**
fixes https://github.com/fredrikekre/jlpkg/commit/4797913f41002874c3b4649e8f83e17792de9e8c#commitcomment-33418965

Edit: better view of diff: https://github.com/JuliaRegistries/Registrator.jl/pull/131/files?w=1

### CODE REVIEW

**Comment by fredrikekre** [comment]
I re-enabled Travis on this repo after the move to this org. Looks like it fails for the new WebUI stuff @christopher-dG

**Comment by nkottary** [comment]
I think we should disable the WebUI tests for travis. It requires secret keys which we can't make public.

**Comment by fredrikekre** [comment]
You can add secret keys as environment variables on travis.

**Comment by nkottary** [comment]
Okay, so I've added `GITHUB_API_TOKEN` env variable in travis settings. @fredrikekre feel free to close and reopen the PR to re-run travis.

**Comment by fredrikekre** [comment]
Seems like something else is wrong then?

**Comment by fredrikekre** [comment]
Disabled the failing test for now.

**Comment by fredrikekre** [comment]
Do we prefer a warning? E.g.
```
The repository name does not end with '.jl', which is a convention used for most Julia packages.
```

**Comment by nkottary** [comment]
This change is deployed.

**Comment by nkottary** [comment]
I think a warning would be good to have. Can you open an issue to discuss whether there needs to be a warning?

**Comment by fredrikekre** [comment]
Will do.

**Pull request merged**
