### PR TITLE
Disable Codecov comments

### PR DESCRIPTION
**Pull request by christopher-dG**
Feel free to disagree, but I get no value from the comments it makes, and code coverage on this project seems to not be a priority in any case.

### CODE REVIEW

**Comment by christopher-dG** [comment]
welp, guess it doesn't work...

**Comment by fredrikekre** [comment]
Yea, I have never gotten this to work...

**Comment by christopher-dG** [comment]
maybe this works...

**Comment by christopher-dG** [comment]
I've been doing some ad hoc testing and I'm not positive, but I think Codecov only reads config from the master branch. So if we merge this then _maybe_ it'll stop yelling at us in future PRs.

**Pull request merged**
