### PR TITLE
Negate some comments

### PR DESCRIPTION
**Pull request by SebRollen**
The inline comments next to some of the options here are confusing as they currently describe the opposite of the behavior specified by the config file.

### CODE REVIEW

**Comment by nkottary** [comment]
Can you change `enable` to `disable` instead of `true` to `false` in the comment? Since the default is `false` I would say that it would read better this way.

**Comment by SebRollen** [comment]
Sure! I updated the comments to reflect that.

It still reads kind of strangely as the comments say that enabling the pull request trigger and approval call is not recommended, yet it's the default option. Perhaps a better fix is to change the actual option in the config file to default to `disable_pull_request_trigger = true` and `disable_approval_process = true`?

**Comment by nkottary** [comment]
Yes, I agree.

**Comment by SebRollen** [comment]
Okay, I updated the defaults to be `true`, and updated the comments to reflect what happens if they're set to `false`. The behavior / language seems much more clear now, in my opinion

**Comment by DilumAluthge** [comment]
@nkottary Is this good to merge now?

**Pull request merged**
