### PR TITLE
Update to RegistryTools@1.3.1.

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by fredrikekre** [comment]
Bump @nkottary can we get this deployed?

**Comment by fredrikekre** [comment]
Bump again @nkottary

**Comment by nkottary** [comment]
Sorry, I messed up my email filter and missed all Registrator notification. I will look at this today.

**Comment by nkottary** [comment]
The deployment is done.

**Comment by fredrikekre** [comment]
Thank you!

**Pull request merged**
